import { CatalogItem } from '../types';

export const DEFAULT_CATALOG_ITEMS: CatalogItem[] = [
  // --- موتور (Engine) ---
  {
    id: 'cat-eng-oil',
    name: 'روغن موتور',
    category: 'موتور',
    recommendedKmInterval: 8000,
    recommendedTimeIntervalMonths: 6,
    warningThresholdKm: 500,
    warningThresholdDays: 14,
    description: 'تعویض روغن موتور مناسب با گرانروی استاندارد سازنده',
  },
  {
    id: 'cat-eng-oil-filter',
    name: 'فیلتر روغن',
    category: 'موتور',
    recommendedKmInterval: 8000,
    recommendedTimeIntervalMonths: 6,
    warningThresholdKm: 500,
    warningThresholdDays: 14,
    description: 'تعویض همزمان با روغن موتور جهت جلوگیری از آلودگی روغن جدید',
  },
  {
    id: 'cat-eng-air-filter',
    name: 'فیلتر هوا',
    category: 'موتور',
    recommendedKmInterval: 10000,
    recommendedTimeIntervalMonths: 6,
    warningThresholdKm: 500,
    warningThresholdDays: 14,
    description: 'تنفس بهتر موتور و کاهش مصرف سوخت',
  },
  {
    id: 'cat-eng-fuel-filter',
    name: 'فیلتر سوخت (بنزین)',
    category: 'موتور',
    recommendedKmInterval: 20000,
    recommendedTimeIntervalMonths: 12,
    warningThresholdKm: 1000,
    warningThresholdDays: 20,
    description: 'جلوگیری از ورود ذرات رسوبی به سوزن‌های انژکتور',
  },
  {
    id: 'cat-eng-spark-plugs',
    name: 'شمع موتور',
    category: 'موتور',
    recommendedKmInterval: 30000,
    recommendedTimeIntervalMonths: 18,
    warningThresholdKm: 1000,
    warningThresholdDays: 30,
    description: 'بهبود احتراق، شتاب بهتر و کاهش مصرف سوخت',
  },
  {
    id: 'cat-eng-timing-belt',
    name: 'تسمه تایم',
    category: 'موتور',
    recommendedKmInterval: 60000,
    recommendedTimeIntervalMonths: 36,
    warningThresholdKm: 2000,
    warningThresholdDays: 45,
    description: 'قطعه بسیار حساس؛ پاره شدن آن به سوپاپ‌ها و موتور آسیب جدی می‌زند',
  },
  {
    id: 'cat-eng-alt-belt',
    name: 'تسمه دینام',
    category: 'موتور',
    recommendedKmInterval: 40000,
    recommendedTimeIntervalMonths: 24,
    warningThresholdKm: 1500,
    warningThresholdDays: 30,
    description: 'انتقال نیرو به دینام، پمپ هیدرولیک و کمپرسور کولر',
  },

  // --- ترمز (Brakes) ---
  {
    id: 'cat-brk-front-pads',
    name: 'لنت ترمز جلو',
    category: 'ترمز',
    recommendedKmInterval: 25000,
    recommendedTimeIntervalMonths: 18,
    warningThresholdKm: 1000,
    warningThresholdDays: 20,
    description: 'ایمنی ترمزگیری و جلوگیری از خط افتادن دیسک ترمز',
  },
  {
    id: 'cat-brk-rear-pads',
    name: 'لنت ترمز عقب',
    category: 'ترمز',
    recommendedKmInterval: 40000,
    recommendedTimeIntervalMonths: 24,
    warningThresholdKm: 1000,
    warningThresholdDays: 20,
    description: 'بازدید لنت‌های کاسه‌ای یا دیسکی عقب',
  },
  {
    id: 'cat-brk-discs',
    name: 'دیسک ترمز',
    category: 'ترمز',
    recommendedKmInterval: 60000,
    recommendedTimeIntervalMonths: 36,
    warningThresholdKm: 2000,
    warningThresholdDays: 30,
    description: 'بررسی لنگی، تاب‌برداشتن و ضخامت استاندارد دیسک',
  },
  {
    id: 'cat-brk-fluid',
    name: 'روغن ترمز',
    category: 'ترمز',
    recommendedKmInterval: 40000,
    recommendedTimeIntervalMonths: 24,
    warningThresholdKm: 1500,
    warningThresholdDays: 30,
    description: 'تعویض به دلیل جذب رطوبت هوا و کاهش نقطه جوش',
  },

  // --- جلوبندی و تعلیق (Suspension) ---
  {
    id: 'cat-susp-shocks',
    name: 'کمک‌فنر',
    category: 'جلوبندی و تعلیق',
    recommendedKmInterval: 70000,
    recommendedTimeIntervalMonths: 48,
    warningThresholdKm: 2000,
    warningThresholdDays: 30,
    description: 'پایداری خودرو و نرمی حرکت در دست‌اندازها',
  },
  {
    id: 'cat-susp-ball-joints',
    name: 'سیبک',
    category: 'جلوبندی و تعلیق',
    recommendedKmInterval: 40000,
    recommendedTimeIntervalMonths: 24,
    warningThresholdKm: 1500,
    warningThresholdDays: 20,
    description: 'کنترل فرمان‌پذیری چرخ‌ها و عدم کشیدگی فرمان',
  },
  {
    id: 'cat-susp-bushings',
    name: 'بوش‌ها',
    category: 'جلوبندی و تعلیق',
    recommendedKmInterval: 40000,
    recommendedTimeIntervalMonths: 24,
    warningThresholdKm: 1500,
    warningThresholdDays: 20,
    description: 'حذف صداهای اضافی و لرزش سیستم تعلیق',
  },
  {
    id: 'cat-susp-control-arm',
    name: 'طبق',
    category: 'جلوبندی و تعلیق',
    recommendedKmInterval: 50000,
    recommendedTimeIntervalMonths: 36,
    warningThresholdKm: 2000,
    warningThresholdDays: 30,
    description: 'اتصال چرخ‌ها به شاسی خودرو',
  },

  // --- سرویس‌های دوره‌ای و عمومی (General Services) ---
  {
    id: 'cat-gen-oil-service',
    name: 'تعویض روغن موتور',
    category: 'سرویس‌های دوره‌ای',
    recommendedKmInterval: 8000,
    recommendedTimeIntervalMonths: 6,
    warningThresholdKm: 500,
    warningThresholdDays: 14,
    description: 'سرویس کامل روغن موتور و روانکاری',
  },
  {
    id: 'cat-gen-gearbox-oil',
    name: 'تعویض روغن گیربکس (واسکازین)',
    category: 'سرویس‌های دوره‌ای',
    recommendedKmInterval: 50000,
    recommendedTimeIntervalMonths: 30,
    warningThresholdKm: 2000,
    warningThresholdDays: 30,
    description: 'روانکاری چرخ‌دنده‌های جعبه‌دنده دستی یا اتوماتیک',
  },
  {
    id: 'cat-gen-ac-service',
    name: 'سرویس کولر و گاز مبرد',
    category: 'سرویس‌های دوره‌ای',
    recommendedKmInterval: 25000,
    recommendedTimeIntervalMonths: 12,
    warningThresholdKm: 1000,
    warningThresholdDays: 30,
    description: 'شارژ گاز، نشت‌یابی و تعویض فیلتر کابین',
  },
  {
    id: 'cat-gen-tune-up',
    name: 'تنظیم موتور (دیاگ و شستشوی انژکتور)',
    category: 'سرویس‌های دوره‌ای',
    recommendedKmInterval: 25000,
    recommendedTimeIntervalMonths: 12,
    warningThresholdKm: 1000,
    warningThresholdDays: 20,
    description: 'بررسی پارامترهای سنسورها، خطایابی و کاهش آلایندگی',
  },
  {
    id: 'cat-gen-wheel-align',
    name: 'میزان فرمان',
    category: 'سرویس‌های دوره‌ای',
    recommendedKmInterval: 15000,
    recommendedTimeIntervalMonths: 12,
    warningThresholdKm: 500,
    warningThresholdDays: 14,
    description: 'جلوگیری از لاستیک‌سایی و حفظ تعادل خودرو در سرعت',
  },
  {
    id: 'cat-gen-wheel-balance',
    name: 'بالانس چرخ',
    category: 'سرویس‌های دوره‌ای',
    recommendedKmInterval: 15000,
    recommendedTimeIntervalMonths: 12,
    warningThresholdKm: 500,
    warningThresholdDays: 14,
    description: 'رفع لرزش فرمان در سرعت‌های بالاتر از ۸۰ ک‌م/ساعت',
  },
  {
    id: 'cat-gen-brake-check',
    name: 'بازدید ترمز',
    category: 'سرویس‌های دوره‌ای',
    recommendedKmInterval: 10000,
    recommendedTimeIntervalMonths: 6,
    warningThresholdKm: 500,
    warningThresholdDays: 14,
    description: 'بررسی ضخامت لنت‌ها، ریگلاژ ترمز دستی و نشتی شیلنگ‌ها',
  },
  {
    id: 'cat-gen-tech-inspect',
    name: 'معاینه فنی',
    category: 'سرویس‌های دوره‌ای',
    recommendedKmInterval: 20000,
    recommendedTimeIntervalMonths: 12,
    warningThresholdKm: 1000,
    warningThresholdDays: 30,
    description: 'بررسی سالانه استاندارد آلایندگی و ایمنی فنی خودرو',
  },
  {
    id: 'cat-gen-coolant',
    name: 'تعویض مایع خنک‌کننده (ضدیخ/ضدجوش)',
    category: 'سرویس‌های دوره‌ای',
    recommendedKmInterval: 40000,
    recommendedTimeIntervalMonths: 24,
    warningThresholdKm: 1500,
    warningThresholdDays: 30,
    description: 'جلوگیری از یخ‌زدگی در زمستان و زنگ‌زدگی بلوک سیلندر و رادیاتور',
  },
  {
    id: 'cat-gen-refuel',
    name: 'سوخت‌گیری',
    category: 'سرویس‌های دوره‌ای',
    recommendedKmInterval: 500,
    recommendedTimeIntervalMonths: 1,
    warningThresholdKm: 50,
    warningThresholdDays: 3,
    description: 'ثبت سوخت‌گیری برای محاسبه مصرف سوخت و هزینه‌ها',
  },
];
